name: IFT3700_PROJETNHL-1
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - ruff
  - pytest
  - pip:
    - python-dotenv
    - mkdocs
    - -e .